[global]
islatlon = true
netcdf_files = ["era5_north_sea_winds_201312_to_201312/era5_winds_201312_43_-15_64_13.nc"]
zarr_file = "era5_north_sea_winds_201312_to_201312.zarr"
xchunk = 141
ychunk = 101
timechunk = 240

    [global.extent]
    ymin = 40.0
    ymax = 65.0
    xmax = 20.0
    xmin = -15.0

[10m_v_component_of_wind]
add_offset = 0.0
data_type = "Int16"
scale_factor = 0.01

[mean_sea_level_pressure]
add_offset = 100000.0
data_type = "Int16"
scale_factor = 1.0

[10m_u_component_of_wind]
add_offset = 0.0
data_type = "Int16"
scale_factor = 0.01
